language: node_js
node_js:
  - node
  - 13
  - 12
  - 11

git:
  - depth: false

jobs:
  include:
    - stage: "FOSSA"
      node_js: node
      before_script:
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
      script:
        - fossa init
        - fossa analyze
      after_success:
      # Set push-only key if regular one is unavailable (i.e. this is a pull-request from a fork).
        - FOSSA_API_KEY="${FOSSA_API_KEY=-78908c4dfc682bcd6fbe2bd38816359c}" fossa test
