name: Windows

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      matrix:
        version: [ 12, 14, 16, 'lts/*', latest ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        check-latest: false
        cache: 'npm'
    - run: npm ci
    - run: npm run coverage:ci
